//! GitHub/Git attribution guardrail (plan section 12).
//!
//! Official GitHub actions (commit messages, trailers, identities, PR/issue
//! text, comments, branch/tag names, release notes) must not carry automatic
//! agent, model or vendor attribution. Detection is phrase-based: it looks for
//! attribution *shapes* (trailers, "generated with ...", session links) rather
//! than blocking every mention of a company name, so legitimate project text
//! such as "Add OpenAI API client" is unaffected.

use std::sync::OnceLock;

use regex::Regex;

const AGENTS: &str = r"(?:claude(?:[\s\-]code)?|anthropic|chat\s?gpt|open\s?ai|gpt[\s\-]?\d[\w.\-]*|codex|(?:github\s+)?copilot|gemini|bard|llama|mistral|cursor(?:\s+ai)?|devin|codeium|windsurf|tabnine|amazon\s+q|codewhisperer|aider|cline|sourcegraph\s+cody|cody|an?\s+ai(?:\s+(?:assistant|agent|model|tool|pair\s+programmer))?|ai[\s\-](?:assistant|agent|model|tool|pair\s+programmer)|(?:large\s+)?language\s+model|llm|coding\s+agent)";

fn patterns() -> &'static [(&'static str, Regex)] {
    static P: OnceLock<Vec<(&'static str, Regex)>> = OnceLock::new();
    P.get_or_init(|| {
        let mk = |label: &'static str, pat: String| (label, Regex::new(&pat).expect("valid attribution regex"));
        vec![
            mk(
                "attribution trailer",
                format!(r"(?im)^\s*(?:co-authored-by|signed-off-by|reviewed-by|helped-by|assisted-by|generated-by|written-by|authored-by)\s*:[^\n]*(?:\b{AGENTS}\b|anthropic\.com|openai\.com|cursor\.(?:sh|com)|codeium\.com)"),
            ),
            mk(
                "generated-with note",
                format!(r"(?i)\b(?:generated|written|created|authored|produced|drafted|assisted|co-?authored|powered|made|built|coded|developed|implemented)\s+(?:entirely\s+|partly\s+|partially\s+)?(?:with|by|using|via|through|in\s+collaboration\s+with)\s+(?:the\s+help\s+of\s+|assistance\s+from\s+)?[\[\(\*_`'\x22]*{AGENTS}\b"),
            ),
            mk(
                "agent session marker",
                r"(?i)\b(?:claude|chatgpt|codex|copilot|cursor|gemini)[\s\-_]session\s*[:=]".to_string(),
            ),
            mk(
                "agent session link",
                r"(?i)(?:claude\.ai/(?:code|chat|share)|chatgpt\.com/(?:codex|share|c/)|chat\.openai\.com/share)".to_string(),
            ),
            mk(
                "robot generated badge",
                r"(?i)🤖\s*(?:generated|created|written|authored)".to_string(),
            ),
        ]
    })
}

/// Returns a short description of the first prohibited attribution found.
pub fn find_attribution(text: &str, extra: &[Regex]) -> Option<String> {
    for (label, re) in patterns() {
        if let Some(m) = re.find(text) {
            return Some(format!("{label}: \"{}\"", truncate(m.as_str(), 80)));
        }
    }
    for re in extra {
        if let Some(m) = re.find(text) {
            return Some(format!("blocked phrase: \"{}\"", truncate(m.as_str(), 80)));
        }
    }
    None
}

/// Identity values (author/committer name or email) that disclose an agent.
pub fn identity_discloses_agent(value: &str) -> bool {
    static R: OnceLock<Regex> = OnceLock::new();
    let re = R.get_or_init(|| {
        Regex::new(&format!(
            r"(?i)(?:\b{AGENTS}\b|anthropic\.com|openai\.com|cursor\.(?:sh|com)|codeium\.com|\[bot\])"
        ))
        .expect("valid regex")
    });
    re.is_match(value)
}

/// Branch or tag names that follow agent-prefixed conventions (`claude/...`).
pub fn ref_name_discloses_agent(name: &str) -> bool {
    static R: OnceLock<Regex> = OnceLock::new();
    let re = R.get_or_init(|| {
        Regex::new(r"(?i)^(?:refs/(?:heads|tags)/)?(?:claude|anthropic|codex|copilot|chatgpt|openai|cursor|devin|gemini|ai-agent|agent|llm)(?:[/_\-]|$)")
            .expect("valid regex")
    });
    re.is_match(name)
}

pub fn compile_extra(patterns: &[String]) -> Vec<Regex> {
    patterns
        .iter()
        .filter_map(|p| Regex::new(&format!("(?i){p}")).ok())
        .collect()
}

fn truncate(s: &str, n: usize) -> String {
    if s.chars().count() <= n {
        s.to_string()
    } else {
        s.chars().take(n).collect::<String>() + "…"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn blocks_attribution_shapes() {
        for t in [
            "Fix bug\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
            "Fix bug\n\nco-authored-by: GitHub Copilot <x@y>",
            "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
            "This PR was generated by ChatGPT",
            "Written with the help of an AI assistant",
            "Created using GPT-4o",
            "Claude-Session: https://claude.ai/code/session_1",
            "See https://chatgpt.com/codex/tasks/123",
            "Drafted with Cursor",
            "Assisted-by: codex",
        ] {
            assert!(find_attribution(t, &[]).is_some(), "not blocked: {t}");
        }
    }

    #[test]
    fn allows_legitimate_mentions() {
        for t in [
            "Add OpenAI API client wrapper",
            "Support Anthropic and OpenAI providers in config",
            "Generated by protoc from service.proto",
            "Fix llama.cpp bindings build on Windows",
            "Bump copilot-language-server dependency",
            "Co-authored-by: Jane Doe <jane@example.com>",
            "Update Claude model id in the example",
        ] {
            assert!(find_attribution(t, &[]).is_none(), "false positive: {t}");
        }
    }

    #[test]
    fn identities_and_refs() {
        assert!(identity_discloses_agent("Claude"));
        assert!(identity_discloses_agent("noreply@anthropic.com"));
        assert!(identity_discloses_agent("dependabot[bot]"));
        assert!(!identity_discloses_agent("Jane Doe"));
        assert!(ref_name_discloses_agent("claude/fix-x"));
        assert!(ref_name_discloses_agent("codex/refactor"));
        assert!(!ref_name_discloses_agent("feature/openai-integration"));
        assert!(!ref_name_discloses_agent("fix-roster"));
    }
}
